# Generated by Django 5.1.5 on 2025-01-23 16:35

import call.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbonentPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_code", models.CharField(max_length=255)),
                (
                    "status",
                    models.IntegerField(
                        default=call.models.CallLineStatus["WaitForResponse"]
                    ),
                ),
                ("initiator_user_id", models.CharField(max_length=64)),
                ("initiator_offer", models.TextField(blank=True)),
                (
                    "initiator_new_ice_routes",
                    models.TextField(blank=True, default="[]"),
                ),
                (
                    "initiator_last_request_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("subscriber_user_id", models.CharField(max_length=64)),
                ("subscriber_answer", models.TextField(blank=True)),
                (
                    "subscriber_new_ice_routes",
                    models.TextField(blank=True, default="[]"),
                ),
                (
                    "subscriber_last_request_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
